[project]
name = "orthant-lance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lancedb>=0.25.2",
    "orthant-documents",
    "pyarrow>=22.0.0",
]
