[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "orthant-documents"
version = "0.1.0"
description = "Orthant documents package"
readme = "README.md"
requires-python = ">=3.13.8"
dependencies = [
    "fsspec>=2025.9.0",
]

[project.optional-dependencies]
test = [
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
]

[tool.setuptools]

[tool.setuptools.packages.find]
where = ["src"]
include = ["orthant*"]

[tool.setuptools.package-dir]
"" = "src"
