[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"

[project]
name = "orthant-embedding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.8"
dependencies = [
    "orthant-documents",
]

[tool.uv.build-backend]
module-name = "orthant.embedding"

[tool.uv.sources]
orthant-documents = { workspace = true }
