[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "orthant-embedding"
version = "0.1.0"
description = "Embeddings support for Orthant"
readme = "README.md"
requires-python = ">=3.13.8"
dependencies = [
    "orthant-documents",
]

[tool.setuptools]

[tool.setuptools.packages.find]
where = ["src"]
include = ["orthant*"]

[tool.setuptools.package-dir]
"" = "src"
