[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "orthant-haystack"
version = "0.1.0"
description = "Haystack utilities for Orthant"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "haystack-ai>=2.19.0",
    "nltk>=3.9.2",
]

[tool.setuptools]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true
include = ["orthant*"]

[tool.setuptools.package-dir]
"" = "src"
